import numpy as np
import math
import matplotlib.pyplot as plt
import scipy.stats as sts
n = np.random.normal(5,1, 1000)
e = np.random.exponential(0.2,1000)
r = np.random.uniform(3,7,1000)
p = np.random.poisson(5,1000)
# norm_rv = sts.norm(loc = 5, scale = 1)
# x = np.linspace(2,8,1000)
# pdf = norm_rv.pdf(x)
# plt.plot(x, pdf)
# plt.hist(n, density=True)
# plt.show()
# plt.close()
# x = np.linspace(0,3,1000)
# expo = sts.expon(scale=0.2)
# pdf =expo.pdf(x)
# plt.plot(x, pdf)
# plt.hist(e, density=True)
# plt.show()
# plt.close()
# x = np.linspace(0,10,1000)
# rand = sts.uniform(3,4)
# pdf = rand.pdf(x)
# plt.plot(x, pdf)
# plt.hist(r, density=True)
# plt.show()
# plt.close()
# x = np.linspace(0,20,21)
# pos = sts.poisson(5)
# pmf = pos.pmf(x)
# un = np.unique(pos.rvs(1000),return_counts=True)
# plt.plot(x, pmf, 'o')
# plt.show()
# plt.close()
# plt.plot(un[0], un[1], '-')
# plt.show()
# plt.close()
x = np.random.choice([1, 2, 3, 4, 5, 6], 30)
# plt.hist(x, 30)
# plt.show()
n = [0,0,0,0,0,0]
y = [1,2,3,4,5,6]
for i in x:
    n[i-1] += 1
plt.plot(y, n, '.-')
plt.xticks(x)
plt.show()
